language: go
go:
- 1.8.x
- 1.9.x
- 1.10.x
- tip
install: true
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get -t ./...
script:
- test -z $(gofmt -s -l $GO_FILES)
- go test -v -race ./...
- go vet ./...
- make linux
deploy:
  provider: bintray
  file: "./descriptor.json"
  user: bharath
  on:
    branch: build-mac
  key:
    secure: UQBRQqtbyw/owpjvoFrZmOV761nSINMio/geK6Z7c/g7O4g65fO4VZfbpU/zbJP5CqiLNWWiF1Go7umdKdgcXUa2tHGEh+y1z0f6I8yiyvAAKbpAjDswhL1Cq7znt0QPGBiDUT/CIVTuuTdv1eJYAasDYdEUS7I/PZOItPO5DUB9qlRg9l6kSRt6mkFMCrT83y3MwlSWxr3wmwN9le10rHvsmkW4Z/On7gYMNgJOl7deQ9ljk5obu2L4TOVXo8veTcEZt7saPddMy9eHtfcFEfbL6GoDi06zCer43UnLtcgVyM/ZtFMJMq3Wx33JooqVJaEdx9elEwhZ78l1Y/ngpDl8ob9aIACObnWaSm2sRrpHRb/Dm/DUNQHkXCsboHAOp0HLNMw2ToBQIV22cRzh8wTEXc/Yb4PjSL6pJHNEcZghfOs71eKD2YJe72I4AgMp4XtoxslC22aH2FWfhMKtd0Ridlf7jWTdLOuncQVB/X8mWdNEhOdNiI2I+ecxh4wjHbvz+KloRE/u6np+VfdGNzbQlhSGwwCR6YJyALJkeOH9LgYf3J4hblpKcEGVQgr5rAoEWBdszWPeE89ycBc6ypbRAURoe+9GZpvpycHKh6PjwxlezgxxtB9aoZveZnlst2NL1vkWJ1lyP0XL+17Uk1yPs5fqCcVMfwGrHkUD58M=
