language: go
go:
- 1.8.x
- 1.9.x
- 1.10.x
- tip
install: true
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get -t ./...
script:
- test -z $(gofmt -s -l $GO_FILES)
- go test -v -race ./...
- go vet ./...
- make linux
deploy:
  provider: bintray
  file: "./descriptor.json"
  user: bharath
  on:
    branch: build-mac
  key:
    secure: dm4wZdX4Csf5UW5mogNK5DfOhSdw96Mc1V2qVVu78x3RWX2DBf6aDjFDewwD5Nt25nzRJO+5W76AXLWc8sEJyL+7/Ku+jcI0mWpqmtHrWG6qWlQFOa+m66GQM7SMHK6g5CiexKjvf5oPIRfVLFjJn/KKMjPisHWwcSgDpq779Or4Lq+t/AD9VW49OSx8kZdi26jpwCEsvf8YZ3uvVKbRR5Imr3dOxtcBxlSUJA+B5qt97Y+zVtUXD0EMEq2/dJ7nCTrb6M6IXxxFFU3nAx3lY7gGHJ9u/7qPrpoRbQ1pmtvVyFU7M2EJ/motf22vC8Aun1nvnxweAaOfGepjg7yalepHr4cHAZGdvwmhTA2LAc6DLQWyEBECxdcTjyAAF/lGUxGsVqwndnvl9D4jwXL9agVi1FHw/nW/RGWzYW494ALJTIBlF3CymSXa42qmiNRgMosSNf681IMOwl3AW/HXHmpLtcagr2wK+dHFg26vTAoeac1mQ2PjcK7ieqPHPoIx4FA28RNhAIlvMGkk9ryDbbG4smYARe9gm3dDy4AVDck0ugFSG1sXNStcVnY1khwjWJh10+Mmqj6sxMOdhiQvpwiH4/TjERi2exujVKjagZ5NcV5iFr30uwK9AIUj72rWhfxvJWiV4xpIZz1cMrZZIa/yOFZyZwIOXFJHufnbKqs=
